NationalGenomicsInfrastructure/LIMS2DB

LIMS2DB/objectsDB/objectsDB.py, LIMS2DB/objectsDB/process_categories.py, scripts/project_summary_upload_LIMS.py, scripts/workset_upload.py
Should improve picking up of miseq projects. No one reported it, but I think I'm onto something
=> cleanup & tentative bugfixing

LIMS2DB/objectsDB/objectsDB.py, docs/process_categories.rst
This adds the workset name to the project object so it can be linked to in genstat.
this also adds several steps in the process_categories file.
=> adding workset name to project object, under sample/lib

LICENSE, LIMS2DB/objectsDB/objectsDB.py, scripts/validation_of_LIMS_upgrade.py
Updated the validation script
Added license
reinforce the logic to not depend as much on the Application UDF
=> prepare for lims changes

LIMS2DB/objectsDB/objectsDB.py
this should help us get the sequencing dates before the demultiplexing step is set up.
=> fixing sequencing dates

LIMS2DB/objectsDB/objectsDB.py
Fixes the current broken lims2db \o/
=> fix isFinLib handling

LIMS2DB/objectsDB/objectsDB.py, scripts/project_summary_upload_LIMS.py
I love the genologics lims. 
I really do. 
This fixes some project breaking  the update schedule.
=> steps actions are hard

scripts/workset_upload.py
This will add some information about the aggregate qc process in the worksets db
=> More fields for the worksets

scripts/workset_upload.py
default date should be none, not 0
=> small things

LIMS2DB/diff.py, LIMS2DB/utils.py, docs/process_categories.rst, scripts/mail_resp.py, scripts/run_diff_with_DB.py, scripts/workset_upload.py
this introduces  a way to assess the changes to the software by comparing the results stored in the DB to those that would be generated by the current version of PSUL.
=> Validation

LIMS2DB/classes.py, LIMS2DB/diff.py, LIMS2DB/objectsDB/objectsDB.py, LIMS2DB/parallel.py, scripts/mail_resp.py, scripts/workset_upload.py
not crawling makes the lc empty, and therefore, no update is performed. so crawling is good.
=> not crawling is bad

LIMS2DB/objectsDB/objectsDB.py
thanks to @senthil10 to have noticed that one
=> fixing finlib projects not showing libprep imformation

scripts/flowcell_summary_uppload_LIMS.py
Now it only looks for `HiSeq` and `MiSeq` processes and update `flowcell` database, this **PR** will also update `x_flowcells`
=> Also update the x_flowcells

LIMS2DB/objectsDB/objectsDB.py
I'm going to need that at some point.
=> adding initial qc plate id

LIMS2DB/objectsDB/objectsDB.py, requirements.txt, scripts/project_summary_upload_LIMS.py, scripts/run_diff_with_DB.py
we'll see how much stuff that changes...
=> adding genologics_sql dependency

scripts/mail_resp.py
The daily mailing script will now also send an email to the responsibles when the project is closed, as requested by Marianna on 2016-02-18
=> update project lab responsibles about project closure

scripts/mail_resp.py
This PR will self destruct in 15 seconds
=> Mission : impossible

LIMS2DB/flowcell_sql.py, LIMS2DB/utils.py, scripts/flowcell_sql_upload.py
This is the basic framework required to replace FSUL, the script that updates the flowcell db with the LIMS data.
=> Thinking about replacements

scripts/workset_upload.py
so we can have even less queries.
=> more db querying

LIMS2DB/flowcell_sql.py, scripts/workset_upload.py
=> Small changes

scripts/mail_resp.py
fixes the script breaking when one of the processes does not have date_run.
=> handle case where date_run is not available

scripts/flowcell_sql_upload.py
Some people apparently still use this. crazy, but real.
=> single flowcell handling

LIMS2DB/classes.py, LIMS2DB/diff.py, LIMS2DB/objectsDB/objectsDB.py, LIMS2DB/objectsDB/process_categories.py, LIMS2DB/parallel.py, scripts/project_summary_upload_LIMS.py
Fixes a workset duplicate issue, and adds the first draft of the project SQL.
=> Updates to LIMS2DB

LIMS2DB/classes.py, scripts/project_summary_upload_LIMS.py
several changes to how PSUL behaves to allow using either the db or the api
=> More PSUL updates

LIMS2DB/classes.py
Tricky case where multiple library validations are run, except they're not real library validations.
=> handling multi libval in small rna

LIMS2DB/classes.py
this handles barcodes for the finished libs samples.
=> handle barcode for finished libs

LIMS2DB/flowcell_sql.py, scripts/mail_resp.py, scripts/workset_upload.py
Specific code for finished libraries, hoping it doesnt mess with small rna like it usually does.
=> smallRNA vs finlib, who will win

LIMS2DB/classes.py
the index searching function did not really like getting "NoIndex"
=> Handles NoIndex samples

LIMS2DB/classes.py, scripts/project_summary_upload_LIMS.py
So we can handled desaborted projects
=> Small QoL updates

LIMS2DB/classes.py
Catches the indexes of the samples for the workset DB
=> adds the parsing of indexes from the DB to the worksets

LIMS2DB/classes.py
Fix for missing concentration in Neoprep Projects.
=> handle missing neoprep concentration

LIMS2DB/classes.py, LIMS2DB/objectsDB/process_categories.py
These changes should allow a better date followup for some small RNA workflows.
=> small changes to fit with the small RNA workflow

scripts/workset_upload_sql.py
Only update the finished setup workset plates
=> Update to the workset update

LIMS2DB/classes.py
Should make PSUL work with odd projects
=> Small fixes

LIMS2DB/classes.py, LIMS2DB/objectsDB/process_categories.py
this saves a link to the fragment analyzer images in couchdb.
=> Fragment Analyzer changes

LIMS2DB/flowcell_sql.py
=> FSQL fix for NovaSeq

LIMS2DB/classes.py
Try to have connection between prep and FC
=> add seqruns to lib prep

LIMS2DB/classes.py
Changed the name of the field 'Uppnex ID' to 'Delivery type'
=> Changed the field Uppnex ID to Delivery type

scripts/mail_resp.py
What SciLifeLab/scilifelab#498 should have been...
=> Update denis' email address to be Pär instead

scripts/mail_resp.py
Added code to mail project coordinators as well in addition to Lab Responsible and Bioinfo responsible when project status changes. In case of names having multiple first/last names, the first word will be taken as first name and the rest of the name as the last name.
=> Project coordinators will now get mail when project status changes

scripts/mail_resp.py
Use account_locked field to check if the account is active before sending mail. Requires the new genologics version to run though.
=> Use fields in new genologics version to check user account to send mail

scripts/updateOrderPortal.py
Fixed a typo that crept in when I saved the file.
=> Fixed typo

scripts/updateOrderPortal.py
The logger outputs the date, so removed the date when using it.
=> Logger takes care of the date

README.md, requirements.txt
I guess the readme could have gone into the private git documentation as well. But some of the information is useful to the public browsing this repo as well.
=> Added a readme with installation instructions

scripts/update_project_min_reads.py
This script was formerly in the now archived scilifelab repo.
=> Update and migrate update_project_min_reads to LIMS2DB

scripts/update_project_min_reads.py
MinION will be added to couchdb once(if?) its in production.
=> Update Reads min script to only update projects with chemistries in couchdb

LIMS2DB/flowcell_sql.py
Saving running notes in the same location for backwards compatibility.
=> Add back fc running notes when running fsul

LIMS2DB/objectsDB/process_categories.py, VERSIONLOG.md, docs/process_categories.rst
Associated with internal validation 23_07.
=> Add support for Illumina DNA PCR-free protocol

LIMS2DB/classes.py, VERSIONLOG.md
=> Update msg format in GA project mail

LIMS2DB/classes.py
=> Save delivery_projects field if present

LIMS2DB/classes.py
Due to change in sqlalchemy function from one to all
=> BugFix: Catch exception for projects without a summary in LIMS

scripts/escalation_running_notes.py
Check with PCs if the mailing group `ngi-project-coordinators@scilifelab.se` is active
=> Add sample names to escalation running notes, and send to PC mailing group if proj has no PC

LIMS2DB/classes.py
=> Add Library method to Application proj update emails

setup.py
Missed something in the last PR https://github.com/SciLifeLab/LIMS2DB/pull/159
=> Convert byte string returned by subprocess

LIMS2DB/objectsDB/process_categories.py, VERSIONLOG.md, docs/process_categories.rst
The old IDs were based on the values on LIMS-stage.
=> Update AVITI step IDs

LIMS2DB/objectsDB/process_categories.py
Possibly additions in more categories?
To be removed from PrepStart when the new ONT workflow is published.
=> Add step to prep start for ONT

LIMS2DB/classes.py
Possible workaround for P34554.
The lab has said that they are phasing out pooling samples in the Aggregate QC step. The condition `len(inp_artifact.samples) > 1` in the `for agrlv in agrlibvals` loop will skip pools since a pool artifact will have multiple samples in it. So to tide over the transition period when some projects will still have pools in Aggregate QC steps, the condition `len(agrlibvals) == 1:` will accept a pool (or a sample) if it is the only item in the Aggregate QC step. If there is more than one pool, LIMS2DB will have to be run manually with workarounds to get the values in StatusDB.
=> Update to use a pooled Aggregate QC step if its the only Aggregate QC step that exists
